/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autorentcar;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class AdminSewaEdit extends javax.swing.JFrame {

    /**
     * Creates new form AdminSewaEdit
     */
    String nik_kar1 = session.get_nik_kar();
    
    Connection koneksi;
    public AdminSewaEdit() {
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_rental");
        comboNamaKar();
        HargaMobil();
        profil();
        ambilNikKar();
        TxtNIK.setEnabled(false);
        TxtNama.setEnabled(false);
        TxtMobil.setEnabled(false);
        TxtNikKar.setVisible(false);
        TxtSelisih.setVisible(false);
        ID_Penyewa.setVisible(false);
        TxtHargaMobil.setVisible(false);
        TxtHargaSewa.setVisible(false);
        cmdEdit.setVisible(false);
    }
    
    String mulai;
    String akhir;
    int TotalBayar;
    int SisaBayar;
    
    public String getTanggal(){
        DateFormat dateformat = new SimpleDateFormat("dd-mm-yyyy");
        Date date = new Date();
        return dateformat.format(date);
    }
    
    public void profil(){
        try{
            Statement stmt = koneksi.createStatement();
            String tampil = "SELECT*FROM karyawan WHERE nik_kar='"+nik_kar1+"'";
            ResultSet rs = stmt.executeQuery(tampil);
            while(rs.next()){
                String nama_kar1 = rs.getString("nama_kar");
                jLabel22.setText(nama_kar1);
            }
        }catch (SQLException ex){
            ex.printStackTrace();
        }
    }
    
    public void comboNamaKar(){
        try{
            String sql = "SELECT nama_kar FROM karyawan WHERE id_jabatan = 3 AND id_status_sopir = 2";
            Statement stmt = koneksi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                
                jComboBox2.addItem(rs.getString("nama_kar"));
            }
            
            rs.close();
            stmt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }
    
    public void HargaMobil(){
        try{
            String sql = "SELECT harga_sewa_mobil FROM kendaraan WHERE no_polisi = '"+TxtMobil.getText()+"'";
            Statement stmt = koneksi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                
                TxtHargaMobil.setText(rs.getString("harga_sewa_mobil"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void ambilNikKar(){
        try{
            String sql = "SELECT nik_kar FROM karyawan WHERE nama_kar = '"+jComboBox2.getSelectedItem()+"'";
            Statement stmt = koneksi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                
                TxtNikKar.setText(rs.getString("nik_kar"));
            }
            
            rs.close();
            stmt.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnKeluar = new javax.swing.JButton();
        BtnPrint = new javax.swing.JButton();
        BtnSewa = new javax.swing.JButton();
        BtnPengeluaran = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TxtNikKar = new javax.swing.JTextField();
        TxtHargaSewa = new javax.swing.JTextField();
        TxtSelisih = new javax.swing.JTextField();
        cmdTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TATotal = new javax.swing.JTextArea();
        cmdPrintStruk = new javax.swing.JButton();
        cmdTotalBayar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jdc_Akhir = new com.toedter.calendar.JDateChooser();
        Jdc_Mulai = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        TxtHp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtDenda = new javax.swing.JTextField();
        TxtHariTelat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAAlamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtNIK = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        TxtHargaMobil = new javax.swing.JTextField();
        TxtMobil = new javax.swing.JTextField();
        TxtSIM = new javax.swing.JTextField();
        cmdEdit = new javax.swing.JButton();
        ID_Penyewa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtKondisi = new javax.swing.JTextArea();
        TxtTotalBayar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        TAStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(107, 189, 71));

        BtnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnKeluar.setForeground(new java.awt.Color(107, 189, 71));
        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        BtnPrint.setBackground(new java.awt.Color(255, 255, 255));
        BtnPrint.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPrint.setForeground(new java.awt.Color(107, 189, 71));
        BtnPrint.setText("Pengaturan");
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });

        BtnSewa.setBackground(new java.awt.Color(255, 255, 255));
        BtnSewa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnSewa.setForeground(new java.awt.Color(107, 189, 71));
        BtnSewa.setText("Sewa");
        BtnSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSewaActionPerformed(evt);
            }
        });

        BtnPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran.setText("Pengeluaran");
        BtnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaranActionPerformed(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo putih.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addGap(72, 72, 72)
                .addComponent(BtnSewa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnKeluar)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(107, 189, 71));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Sewa");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Hai ,");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("There");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        cmdTambah.setBackground(new java.awt.Color(255, 255, 255));
        cmdTambah.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cmdTambah.setForeground(new java.awt.Color(107, 189, 71));
        cmdTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-267-705688.png"))); // NOI18N
        cmdTambah.setText("Kembalikan");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        TATotal.setColumns(20);
        TATotal.setRows(5);
        jScrollPane2.setViewportView(TATotal);

        cmdPrintStruk.setBackground(new java.awt.Color(255, 255, 255));
        cmdPrintStruk.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cmdPrintStruk.setForeground(new java.awt.Color(107, 189, 71));
        cmdPrintStruk.setText("Print Struk");
        cmdPrintStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintStrukActionPerformed(evt);
            }
        });

        cmdTotalBayar.setBackground(new java.awt.Color(255, 255, 255));
        cmdTotalBayar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cmdTotalBayar.setForeground(new java.awt.Color(107, 189, 71));
        cmdTotalBayar.setText("Total Bayar");
        cmdTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTotalBayarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berkendara Sendiri", "Berkendara Dengan Sopir" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(107, 189, 71));
        jLabel10.setText("Status Sewa");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(107, 189, 71));
        jLabel9.setText("Tanggal Berakhir");

        Jdc_Akhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Jdc_AkhirPropertyChange(evt);
            }
        });

        Jdc_Mulai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Jdc_MulaiPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(107, 189, 71));
        jLabel8.setText("Tanggal Mulai");

        TxtHp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHpActionPerformed(evt);
            }
        });
        TxtHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtHpKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 189, 71));
        jLabel5.setText("No HP");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(107, 189, 71));
        jLabel16.setText("Keterlambatan");

        TxtDenda.setText("50000");

        TxtHariTelat.setText("0");

        TAAlamat.setColumns(20);
        TAAlamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TAAlamat.setRows(5);
        jScrollPane1.setViewportView(TAAlamat);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 189, 71));
        jLabel4.setText("Alamat");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 189, 71));
        jLabel3.setText("Nama");

        TxtNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(107, 189, 71));
        jLabel7.setText("NIK");

        TxtNIK.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNIKActionPerformed(evt);
            }
        });
        TxtNIK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNIKKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 189, 71));
        jLabel6.setText("Edit Data");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(107, 189, 71));
        jLabel11.setText("No SIM");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(107, 189, 71));
        jLabel12.setText("Mobil");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(107, 189, 71));
        jLabel13.setText("Sopir");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        TxtSIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSIMKeyTyped(evt);
            }
        });

        cmdEdit.setBackground(new java.awt.Color(255, 255, 255));
        cmdEdit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cmdEdit.setForeground(new java.awt.Color(107, 189, 71));
        cmdEdit.setText("Edit");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(107, 189, 71));
        jLabel18.setText("Kondisi Mobil");

        TxtKondisi.setColumns(20);
        TxtKondisi.setRows(5);
        jScrollPane3.setViewportView(TxtKondisi);

        TxtTotalBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTotalBayarKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(107, 189, 71));
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(107, 189, 71));
        jLabel17.setText("Baru Bayar");

        TAStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TAStatusKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel6)
                        .addContainerGap(320, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(30, 30, 30)
                                        .addComponent(Jdc_Mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel12))
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TxtMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Jdc_Akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(24, 24, 24)
                                        .addComponent(jScrollPane3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TxtNikKar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(139, 139, 139)
                                            .addComponent(TxtHargaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ID_Penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel3))
                                                .addGap(26, 26, 26))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtHp)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(TxtNama)
                                            .addComponent(TxtNIK))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cmdTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmdPrintStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cmdEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdTambah))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TxtDenda)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtHariTelat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TxtTotalBayar)
                                            .addComponent(TAStatus)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(84, 84, 84)
                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(64, 64, 64)
                                        .addComponent(TxtSIM)))))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(TxtSIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtHp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jdc_Mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(Jdc_Akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNikKar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_Penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtHargaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtHariTelat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TAStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdTotalBayar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdPrintStruk)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        String pilih[] = {"IYA","BATALKAN"};
        int keluar = JOptionPane.showOptionDialog(this,
            "Apakah anda yakin ingin keluar ?", "Keluar Program",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, pilih, pilih);

        if (keluar == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program keluar");
            System.exit(WIDTH);
        }
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        // TODO add your handling code here: 
        AdminPengaturan ap = new AdminPengaturan();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSewaActionPerformed
        // TODO add your handling code here:
        MenuAdmin ma = new MenuAdmin();
        ma.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnSewaActionPerformed

    private void BtnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaranActionPerformed
        // TODO add your handling code here:
        AdminPengeluaran Apeng = new AdminPengeluaran();
        Apeng.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaranActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE kendaraan SET id_status = 2 WHERE no_polisi = '"+TxtMobil.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi;
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            String sql2 = "UPDATE sewa SET status_transaksi = 'Selesai Digunakan', kondisi_sewa = '"+TxtKondisi.getText()+"', keterlambatan = '"+TxtHariTelat.getText()+"', total_bayar_sewa = '"+TxtTotalBayar.getText()+"' WHERE id_penyewa = '"+ID_Penyewa.getText()+"'";
            java.sql.Connection kon=(Connection)koneksi;
            java.sql.PreparedStatement pst2=kon.prepareStatement(sql2);
            pst2.execute();
            String sql3 = "UPDATE karyawan SET id_status_sopir = 2 WHERE nik_kar = '"+TxtNikKar.getText()+"'";
            java.sql.Connection kon3=(Connection)koneksi;
            java.sql.PreparedStatement pst3=kon3.prepareStatement(sql3);
            pst3.execute();
            JOptionPane.showMessageDialog(null, "Mobil sudah dikembalikan");
            MenuAdmin ma = new MenuAdmin();
            ma.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdPrintStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintStrukActionPerformed
        // TODO add your handling code here:
        try{
            boolean complete = TATotal.print();
            if (complete) {

            }else{

            }
        }catch(PrinterException pe){

        }
    }//GEN-LAST:event_cmdPrintStrukActionPerformed

    private void cmdTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTotalBayarActionPerformed
        // TODO add your handling code here:
        SisaBayar = SisaBayar+Integer.valueOf(Integer.valueOf(TxtTotalBayar.getText())- Integer.valueOf(TAStatus.getText()));
        //TxtTotalBayar.setText(String.valueOf(TotalBayar));
        
        AdminSewaTambah tgl = new AdminSewaTambah();
        
        String name = TxtNama.getText();
        String start = mulai;
        String end = akhir;
        String status_sewa = (String)jComboBox1.getSelectedItem();
        String plat_mobil = TxtMobil.getText();
        String sopir = (String)jComboBox2.getSelectedItem();
        String status_bayar = TAStatus.getText();
        String hari_lambat = TxtHariTelat.getText();
        String total = TxtTotalBayar.getText();
        String sisa = String.valueOf(SisaBayar);
        TATotal.setText("  Selamat Datang Di Tempat Rental "+"\n"+
                    "\t      Robbani Corporation "+"\n"+
                    "\tJl. Soekarno-Hatta No.378       "+"\n"+
                    "\t    (022) 5224000"+"\n"+
                    "======================================"+"\n"+
                    "\t      "+tgl.getTanggal()+"\n"+
                    "======================================"+"\n"+
                    "Nama Penyewa             \t : "+name+"\n"+
                    "Tanggal Sewa   \t : "+start+"\n"+
                    "Tanggal Akhir          \t : "+end+"\n"+
                    "Status Sewa         \t : "+status_sewa+"\n"+
                    "Nomor Polisi       \t : "+plat_mobil+"\n"+
                    "Sopir       \t\t : "+sopir+"\n"+
                    "Total Bayar       \t : Rp."+total+"\n"+
                    "Yang Sudah diBayar       \t : "+status_bayar+"\n"+
                    "Keterlambatan       \t : "+hari_lambat+" hari"+"\n"+
                    "Sisa Bayar       \t : Rp."+sisa+" "+"\n"+
                    "======================================"+"\n"+
                    "                        TERIMA KASIH       "+"\n"+
                    "======================================"
                );
    }//GEN-LAST:event_cmdTotalBayarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem() == "Berkendara Sendiri") {
            TxtHargaSewa.setText("0");
            jLabel11.setVisible(true);
            TxtSIM.setVisible(true);
            jLabel13.setVisible(false);
            jComboBox2.setVisible(false);
        }else if (jComboBox1.getSelectedItem() == "Berkendara Dengan Sopir") {
            TxtHargaSewa.setText("100000");
            jLabel13.setVisible(true);
            jComboBox2.setVisible(true);
            jLabel11.setVisible(false);
            TxtSIM.setVisible(false);
        }
        try {
            DateFormat format = new SimpleDateFormat("dd MMMM yyyy");
            Date tanggalmulai = format.parse(mulai);
            Date tanggalakhir = format.parse(akhir);
            long tanggalmulai1 = tanggalmulai.getTime();
            long tanggalakhir1 = tanggalakhir.getTime();
            long diff = tanggalakhir1 - tanggalmulai1;
            long lama = diff / (24 * 60 * 60 * 1000);
            TxtSelisih.setText(Long.toString(lama) + "");
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Jdc_AkhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Jdc_AkhirPropertyChange
        // TODO add your handling code here:
        if (Jdc_Akhir.getDate() != null) {
            SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
            akhir = FormatTanggal.format(Jdc_Akhir.getDate());
        }
    }//GEN-LAST:event_Jdc_AkhirPropertyChange

    private void Jdc_MulaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Jdc_MulaiPropertyChange
        // TODO add your handling code here:
        if (Jdc_Mulai.getDate() != null) {
            SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
            mulai = FormatTanggal.format(Jdc_Mulai.getDate());
        }
    }//GEN-LAST:event_Jdc_MulaiPropertyChange

    private void TxtHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHpActionPerformed

    private void TxtHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtHpKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TxtHpKeyTyped

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaActionPerformed

    private void TxtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNIKActionPerformed

    private void TxtNIKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNIKKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TxtNIKKeyTyped

    private void TxtSIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSIMKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TxtSIMKeyTyped

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal_mulai = String.valueOf(fm.format(Jdc_Mulai.getDate()));
        String tanggal_akhir = String.valueOf(fm.format(Jdc_Akhir.getDate()));
        String total = String.valueOf(TotalBayar);
        try{
            String sql = "UPDATE sewa SET nik_penyewa = '"+TxtNIK.getText()+"', nama_penyewa = '"+TxtNama.getText()+"', alamat_penyewa = '"+TAAlamat.getText()+"', "
                    + "no_hp_penyewa = '"+TxtHp.getText()+"', no_sim_penyewa = '"+TxtSIM.getText()+"', tgl_mulai_sewa = '"+tanggal_mulai+"', tgl_akhir_sewa = '"+tanggal_akhir+"',"
                    + "status_sewa = '"+jComboBox1.getSelectedItem()+"', no_polisi = '"+TxtMobil.getText()+"', nik_kar = '"+TxtNikKar.getText()+"', status_bayar = '"+TAStatus.getText()+"',"
                            + "keterlambatan = '"+TxtHariTelat.getText()+"', total_bayar_sewa = '"+total+"', kondisi_sewa = '"+TxtKondisi.getText()+"' WHERE id_penyewa = '"+ID_Penyewa.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi;
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        MenuAdmin ma = new MenuAdmin();
        ma.setVisible(true);
        dispose();
    }//GEN-LAST:event_cmdEditActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        ambilNikKar();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void TxtTotalBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTotalBayarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalBayarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TotalBayar = TotalBayar+Integer.valueOf(Integer.valueOf(TxtSelisih.getText())*
            (Integer.valueOf(TxtHargaSewa.getText())+Integer.valueOf(TxtHargaMobil.getText()))+
            (Integer.valueOf(TxtDenda.getText())*Integer.valueOf(TxtHariTelat.getText())));
        TxtTotalBayar.setText(String.valueOf(TotalBayar));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TAStatusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TAStatusKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TAStatusKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSewaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSewaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSewaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSewaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSewaEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnPengeluaran;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JButton BtnSewa;
    public javax.swing.JTextField ID_Penyewa;
    public com.toedter.calendar.JDateChooser Jdc_Akhir;
    public com.toedter.calendar.JDateChooser Jdc_Mulai;
    public javax.swing.JTextArea TAAlamat;
    public javax.swing.JTextField TAStatus;
    private javax.swing.JTextArea TATotal;
    private javax.swing.JTextField TxtDenda;
    public javax.swing.JTextField TxtHargaMobil;
    private javax.swing.JTextField TxtHargaSewa;
    public javax.swing.JTextField TxtHariTelat;
    public javax.swing.JTextField TxtHp;
    private javax.swing.JTextArea TxtKondisi;
    public javax.swing.JTextField TxtMobil;
    public javax.swing.JTextField TxtNIK;
    public javax.swing.JTextField TxtNama;
    public javax.swing.JTextField TxtNikKar;
    public javax.swing.JTextField TxtSIM;
    private javax.swing.JTextField TxtSelisih;
    private javax.swing.JTextField TxtTotalBayar;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdPrintStruk;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JButton cmdTotalBayar;
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
