/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autorentcar;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class SAPengaturan extends javax.swing.JFrame {

    /**
     * Creates new form SAPengaturan
     */
    String nik_kar1 = session.get_nik_kar();
    String username1 = session.get_username();
    
    Connection koneksi;
    public SAPengaturan() {
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_rental");
        labelCekMatchPassword.setText("");
        TxtUsername.setText(username1);
        TxtUsername.setEnabled(false);
        profil();
    }

    public void profil(){
        try{
            Statement stmt = koneksi.createStatement();
            String tampil = "SELECT*FROM karyawan WHERE nik_kar='"+nik_kar1+"'";
            ResultSet rs = stmt.executeQuery(tampil);
            while(rs.next()){
                String nama_kar1 = rs.getString("nama_kar");
                jLabel17.setText(nama_kar1);
            }
        }catch (SQLException ex){
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnKeluar = new javax.swing.JButton();
        BtnKerusakan = new javax.swing.JButton();
        BtnSewa = new javax.swing.JButton();
        BtnPengeluaran = new javax.swing.JButton();
        BtnPengeluaran1 = new javax.swing.JButton();
        BtnPengeluaran2 = new javax.swing.JButton();
        BtnPengeluaran3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmdGanti = new javax.swing.JButton();
        PasswordBaru = new javax.swing.JPasswordField();
        PasswordKonfirm = new javax.swing.JPasswordField();
        PasswordLama = new javax.swing.JPasswordField();
        TxtUsername = new javax.swing.JTextField();
        labelCekMatchPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(107, 189, 71));

        BtnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnKeluar.setForeground(new java.awt.Color(107, 189, 71));
        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        BtnKerusakan.setBackground(new java.awt.Color(255, 255, 255));
        BtnKerusakan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnKerusakan.setForeground(new java.awt.Color(107, 189, 71));
        BtnKerusakan.setText("Pengeluaran");
        BtnKerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKerusakanActionPerformed(evt);
            }
        });

        BtnSewa.setBackground(new java.awt.Color(255, 255, 255));
        BtnSewa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnSewa.setForeground(new java.awt.Color(107, 189, 71));
        BtnSewa.setText("Sewa");
        BtnSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSewaActionPerformed(evt);
            }
        });

        BtnPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran.setText("Karyawan");
        BtnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaranActionPerformed(evt);
            }
        });

        BtnPengeluaran1.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran1.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran1.setText("Kendaraan");
        BtnPengeluaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaran1ActionPerformed(evt);
            }
        });

        BtnPengeluaran2.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran2.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran2.setText("User");
        BtnPengeluaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaran2ActionPerformed(evt);
            }
        });

        BtnPengeluaran3.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran3.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran3.setText("Pengaturan");
        BtnPengeluaran3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaran3ActionPerformed(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo putih.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnKerusakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(BtnSewa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnKerusakan)
                .addGap(5, 5, 5)
                .addComponent(BtnPengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPengeluaran1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPengeluaran2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPengeluaran3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnKeluar)
                .addGap(109, 109, 109))
        );

        jPanel5.setBackground(new java.awt.Color(107, 189, 71));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data User");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Hai ,");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("There");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 189, 71));
        jLabel6.setText("Ganti Password");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(107, 189, 71));
        jLabel14.setText("Username");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(107, 189, 71));
        jLabel13.setText("Password Lama ");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(107, 189, 71));
        jLabel15.setText("Password Konfirmasi ");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(107, 189, 71));
        jLabel18.setText("Password Baru");

        cmdGanti.setBackground(new java.awt.Color(255, 255, 255));
        cmdGanti.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cmdGanti.setForeground(new java.awt.Color(107, 189, 71));
        cmdGanti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/163-1630210_how-to-change-your-account-password-password-icon-png-green.jpg"))); // NOI18N
        cmdGanti.setText("Ganti");
        cmdGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGantiActionPerformed(evt);
            }
        });

        PasswordKonfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKonfirmKeyReleased(evt);
            }
        });

        labelCekMatchPassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        labelCekMatchPassword.setForeground(new java.awt.Color(107, 189, 71));
        labelCekMatchPassword.setText("Cek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PasswordKonfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCekMatchPassword))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(51, 51, 51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmdGanti)
                                        .addGap(118, 118, 118)))))
                        .addGap(172, 172, 172))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(PasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(PasswordKonfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCekMatchPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(PasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdGanti, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        String pilih[] = {"IYA","BATALKAN"};
        int keluar = JOptionPane.showOptionDialog(this,
            "Apakah anda yakin ingin keluar ?", "Keluar Program",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, pilih, pilih);

        if (keluar == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program keluar");
            System.exit(WIDTH);
        }
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKerusakanActionPerformed
        // TODO add your handling code here:
        SAPengeluaran sapeng = new SAPengeluaran();
        sapeng.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnKerusakanActionPerformed

    private void BtnSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSewaActionPerformed
        // TODO add your handling code here:
        MenuSA MSA = new MenuSA();
        MSA.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnSewaActionPerformed

    private void BtnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaranActionPerformed
        // TODO add your handling code here:
        SAKaryawan sakar = new SAKaryawan();
        sakar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaranActionPerformed

    private void BtnPengeluaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaran1ActionPerformed
        // TODO add your handling code here:
        SAKendaraan sak = new SAKendaraan();
        sak.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaran1ActionPerformed

    private void BtnPengeluaran2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaran2ActionPerformed
        // TODO add your handling code here:
        SAUser SAU = new SAUser();
        SAU.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaran2ActionPerformed

    private void BtnPengeluaran3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaran3ActionPerformed
        // TODO add your handling code here:
        SAPengaturan sap = new SAPengaturan();
        sap.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaran3ActionPerformed

    private void cmdGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGantiActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM user WHERE username='"+TxtUsername.getText()+"' AND password='"+PasswordLama.getText()+"'";
            Statement stat = koneksi.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                if(TxtUsername.getText().equals(rs.getString("username")) && PasswordLama.getText().equals(rs.getString("password"))){
                    String sql2 = "UPDATE user SET password = '"+PasswordBaru.getText()+"' WHERE username='"+TxtUsername.getText()+"'";
                    java.sql.Connection conn=(Connection)koneksi;
                    java.sql.PreparedStatement pst=conn.prepareStatement(sql2);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "password berhasil diubah");
                    LogIn l = new LogIn();
                    l.setVisible(true);
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "password salah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdGantiActionPerformed

    private void PasswordKonfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKonfirmKeyReleased
        // TODO add your handling code here:
        String registerPassword = new String (PasswordLama.getPassword());
        String retypePassword = new String (PasswordKonfirm.getPassword());
        if (registerPassword.equals(retypePassword)) {
            labelCekMatchPassword.setText("Password Sama");
        }
        else if (!registerPassword.equals(retypePassword)) {
            labelCekMatchPassword.setText("Password Tidak Sama");
        }
    }//GEN-LAST:event_PasswordKonfirmKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAPengaturan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnKerusakan;
    private javax.swing.JButton BtnPengeluaran;
    private javax.swing.JButton BtnPengeluaran1;
    private javax.swing.JButton BtnPengeluaran2;
    private javax.swing.JButton BtnPengeluaran3;
    private javax.swing.JButton BtnSewa;
    private javax.swing.JPasswordField PasswordBaru;
    private javax.swing.JPasswordField PasswordKonfirm;
    private javax.swing.JPasswordField PasswordLama;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JButton cmdGanti;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelCekMatchPassword;
    // End of variables declaration//GEN-END:variables
}
