/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autorentcar;

import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hp
 */
public class SAUser extends javax.swing.JFrame {

    /**
     * Creates new form SAUser
     */
    String nik_kar1 = session.get_nik_kar();
    
    Connection koneksi;
    public SAUser() {
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_rental");
        PlaceHolder holder1 = new PlaceHolder(TxtCari, "Cari Pengguna");
        showData();
        profil();
    }

    public void profil(){
        try{
            Statement stmt = koneksi.createStatement();
            String tampil = "SELECT*FROM karyawan WHERE nik_kar='"+nik_kar1+"'";
            ResultSet rs = stmt.executeQuery(tampil);
            while(rs.next()){
                String nama_kar1 = rs.getString("nama_kar");
                jLabel17.setText(nama_kar1);
            }
        }catch (SQLException ex){
            ex.printStackTrace();
        }
    }
    
    DefaultTableModel dtm;
    public void showData(){
        String[] kolom = {"NO","Nama Karyawan","Username","Jabatan","Hak Akses"};
        
        dtm = new DefaultTableModel(null, kolom);
        try{
            Statement stmt = koneksi.createStatement();
            String query = "SELECT k.nama_kar, u.username, j.nama_jabatan, ha.nama_hak_akses FROM user AS u INNER JOIN hak_akses AS ha ON u.id_hak_akses = ha.id_hak_akses INNER JOIN karyawan AS k ON u.nik_kar = k.nik_kar INNER JOIN jabatan AS j ON k.id_jabatan = j.id_jabatan ";
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while (rs.next()){
                String nama_kar = rs.getString("nama_kar");
                String username = rs.getString("username");
                String nama_jabatan = rs.getString("nama_jabatan");
                String nama_hak_akses = rs.getString("nama_hak_akses");
                
                dtm.addRow(new String[]{no+"",nama_kar,username,nama_jabatan,nama_hak_akses});
                no++;
            }
        }catch (SQLException ex){
            ex.printStackTrace();
        }
        tbl_user.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtCari = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        BtnCari = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnKeluar = new javax.swing.JButton();
        BtnKerusakan = new javax.swing.JButton();
        BtnSewa = new javax.swing.JButton();
        BtnPengeluaran = new javax.swing.JButton();
        BtnPengeluaran1 = new javax.swing.JButton();
        BtnPengeluaran2 = new javax.swing.JButton();
        BtnPengeluaran3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();
        cmdTambah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TxtCari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtCari.setBorder(null);

        BtnCari.setBackground(new java.awt.Color(255, 255, 255));
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search icon.png"))); // NOI18N
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(107, 189, 71));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data User");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Hai ,");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("There");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(107, 189, 71));

        BtnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnKeluar.setForeground(new java.awt.Color(107, 189, 71));
        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        BtnKerusakan.setBackground(new java.awt.Color(255, 255, 255));
        BtnKerusakan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnKerusakan.setForeground(new java.awt.Color(107, 189, 71));
        BtnKerusakan.setText("Pengeluaran");
        BtnKerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKerusakanActionPerformed(evt);
            }
        });

        BtnSewa.setBackground(new java.awt.Color(255, 255, 255));
        BtnSewa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnSewa.setForeground(new java.awt.Color(107, 189, 71));
        BtnSewa.setText("Sewa");
        BtnSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSewaActionPerformed(evt);
            }
        });

        BtnPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran.setText("Karyawan");
        BtnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaranActionPerformed(evt);
            }
        });

        BtnPengeluaran1.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran1.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran1.setText("Kendaraan");
        BtnPengeluaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaran1ActionPerformed(evt);
            }
        });

        BtnPengeluaran2.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran2.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran2.setText("User");
        BtnPengeluaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaran2ActionPerformed(evt);
            }
        });

        BtnPengeluaran3.setBackground(new java.awt.Color(255, 255, 255));
        BtnPengeluaran3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnPengeluaran3.setForeground(new java.awt.Color(107, 189, 71));
        BtnPengeluaran3.setText("Pengaturan");
        BtnPengeluaran3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPengeluaran3ActionPerformed(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo putih.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnKerusakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPengeluaran3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(BtnSewa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnKerusakan)
                .addGap(5, 5, 5)
                .addComponent(BtnPengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPengeluaran1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPengeluaran2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPengeluaran3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnKeluar)
                .addGap(109, 109, 109))
        );

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_user);

        cmdTambah.setBackground(new java.awt.Color(255, 255, 255));
        cmdTambah.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cmdTambah.setForeground(new java.awt.Color(107, 189, 71));
        cmdTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tambah.png"))); // NOI18N
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdHapus.setBackground(new java.awt.Color(255, 255, 255));
        cmdHapus.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cmdHapus.setForeground(new java.awt.Color(107, 189, 71));
        cmdHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete icon.png"))); // NOI18N
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCari)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdHapus))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        // TODO add your handling code here:
        String cari = TxtCari.getText();
        int clean = dtm.getRowCount();
        for (int i = 0; i < clean; i++) {
            dtm.removeRow(0);
        }
        try{
            Statement stmt = koneksi.createStatement();
            String sql = ("SELECT k.nama_kar, u.username, j.nama_jabatan, ha.nama_hak_akses FROM user AS u INNER JOIN hak_akses AS ha ON u.id_hak_akses = ha.id_hak_akses INNER JOIN karyawan AS k ON u.nik_kar = k.nik_kar INNER JOIN jabatan AS j ON k.id_jabatan = j.id_jabatan WHERE username LIKE '%"+cari+"%' OR nama_kar LIKE '%"+cari+"%' OR nama_jabatan LIKE '%"+cari+"%' OR nama_hak_akses LIKE '%"+cari+"%'; ");
            ResultSet rs = stmt.executeQuery(sql);
            int no = 1;
            while (rs.next()){
                String nama_kar = rs.getString("nama_kar");
                String username = rs.getString("username");
                String nama_jabatan = rs.getString("nama_jabatan");
                String nama_hak_akses = rs.getString("nama_hak_akses");
                
                dtm.addRow(new String[]{no+"",nama_kar,username,nama_jabatan,nama_hak_akses});
                no++;
            }
            tbl_user.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        String pilih[] = {"IYA","BATALKAN"};
        int keluar = JOptionPane.showOptionDialog(this,
            "Apakah anda yakin ingin keluar ?", "Keluar Program",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, pilih, pilih);

        if (keluar == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program keluar");
            System.exit(WIDTH);
        }
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKerusakanActionPerformed
        // TODO add your handling code here:
        SAPengeluaran sapeng = new SAPengeluaran();
        sapeng.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnKerusakanActionPerformed

    private void BtnSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSewaActionPerformed
        // TODO add your handling code here:
        MenuSA MSA = new MenuSA();
        MSA.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnSewaActionPerformed

    private void BtnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaranActionPerformed
        // TODO add your handling code here:
        SAKaryawan sakar = new SAKaryawan();
        sakar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaranActionPerformed

    private void BtnPengeluaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaran1ActionPerformed
        // TODO add your handling code here:
        SAKendaraan sak = new SAKendaraan();
        sak.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaran1ActionPerformed

    private void BtnPengeluaran2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaran2ActionPerformed
        // TODO add your handling code here:
        SAUser SAU = new SAUser();
        SAU.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaran2ActionPerformed

    private void BtnPengeluaran3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPengeluaran3ActionPerformed
        // TODO add your handling code here:
        SAPengaturan sap = new SAPengaturan();
        sap.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPengeluaran3ActionPerformed

    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked
        // TODO add your handling code here:
    /*    int baris = tbl_user.rowAtPoint(evt.getPoint());
        TableModel model = tbl_user.getModel();
        String nama =tbl_user.getValueAt(baris, 1).toString();
        String tgl_mulai = tbl_user.getValueAt(baris,2).toString();
        String tgl_akhir = tbl_user.getValueAt(baris, 3).toString();
        String status = tbl_user.getValueAt(baris, 4).toString();
        String no_polisi = tbl_user.getValueAt(baris, 5).toString();
        try{
            Statement stmt = koneksi.createStatement();
            String sql = ("SELECT id_penyewa FROM sewa WHERE nama_penyewa = '"+nama+"' AND tgl_mulai_sewa = '"+tgl_mulai+"'"
                + "AND tgl_akhir_sewa = '"+tgl_akhir+"' AND status_sewa = '"+status+"' AND no_polisi = '"+no_polisi+"';");
            ResultSet result = stmt.executeQuery(sql);
            int no = 1;
            while (result.next()){
                jTextField2.setText(result.getString("id_penyewa"));
                String IdPenyewa = result.getString("id_penyewa");
                ase.ID_Penyewa.setText(IdPenyewa);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        try{
            String sql = "SELECT * FROM sewa WHERE id_penyewa = '"+jTextField2.getText()+"'";
            Statement stmt = koneksi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String nik_penyewa = rs.getString("nik_penyewa");
                String nama_penyewa = rs.getString("nama_penyewa");
                String alamat_penyewa = rs.getString("alamat_penyewa");
                String hp_penyewa = rs.getString("no_hp_penyewa");
                String sim_penyewa = rs.getString("no_sim_penyewa");
                String tgl_mulai_sewa = rs.getString("tgl_mulai_sewa");
                String tgl_akhir_sewa = rs.getString("tgl_akhir_sewa");
                String status_sewa = rs.getString("status_sewa");
                String status_bayar_sewa = rs.getString("status_bayar");
                String no_polisi_sewa = rs.getString("no_polisi");
                String nik_kar = rs.getString("nik_kar");
                String keterlambatan  = rs.getString("keterlambatan");
                NIK_KAR.setText(rs.getString("nik_kar"));

                Date dateStart = new SimpleDateFormat("yyyy-MM-dd").parse(tgl_mulai_sewa);
                Date dateEnd = new SimpleDateFormat("yyyy-MM-dd").parse(tgl_akhir_sewa);
                ase.TxtNIK.setText(nik_penyewa);
                ase.TxtNama.setText(nama_penyewa);
                ase.TAAlamat.setText(alamat_penyewa);
                ase.TxtHp.setText(hp_penyewa);
                ase.TxtSIM.setText(sim_penyewa);
                ase.Jdc_Mulai.setDate(dateStart);
                ase.Jdc_Akhir.setDate(dateEnd);
                ase.jComboBox1.setSelectedItem(status_sewa);
                ase.TAStatus.setText(status_bayar_sewa);
                ase.TxtMobil.setText(no_polisi);
                ase.TxtNikKar.setText(nik_kar);
                ase.TxtHariTelat.setText(keterlambatan);
            }
            String sql2 = "SELECT nama_kar FROM karyawan WHERE nik_kar = '"+NIK_KAR.getText()+"'";
            Statement stmt2 = koneksi.createStatement();
            ResultSet rs2 = stmt2.executeQuery(sql2);
            while (rs2.next()){
                String nama_kar = rs2.getString("nama_kar");
                ase.jComboBox2.setSelectedItem(nama_kar);
            }

            String sql3 = "SELECT harga_sewa_mobil FROM kendaraan WHERE no_polisi = '"+no_polisi+"'";
            Statement stmt3 = koneksi.createStatement();
            ResultSet rs3 = stmt2.executeQuery(sql3);
            while (rs3.next()){
                String harga_sewa_mobil = rs3.getString("harga_sewa_mobil");
                ase.TxtHargaMobil.setText(harga_sewa_mobil);
            }
            rs.close();
            stmt.close();

        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }*/
    }//GEN-LAST:event_tbl_userMouseClicked

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        // TODO add your handling code here:
        SAUserTambah saut = new SAUserTambah();
        saut.setVisible(true);
        dispose();
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        // TODO add your handling code here:
        int baris = tbl_user.getSelectedRow();
        String username = tbl_user.getValueAt(baris, 2).toString();
        String pilihan[] = {"IYA","BATALKAN"};
        int keluar = JOptionPane.showOptionDialog(this,
            "Apakah anda yakin ingin menghapus user "+username+" ?", "Hapus Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, pilihan, pilihan[0]);

        if (keluar == JOptionPane.YES_OPTION){
            try {
                String sql ="delete from user where username='"+username+"'";
                java.sql.Connection conn=(Connection)koneksi;
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "user berhasil di hapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            this.showData();
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnKerusakan;
    private javax.swing.JButton BtnPengeluaran;
    private javax.swing.JButton BtnPengeluaran1;
    private javax.swing.JButton BtnPengeluaran2;
    private javax.swing.JButton BtnPengeluaran3;
    private javax.swing.JButton BtnSewa;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tbl_user;
    // End of variables declaration//GEN-END:variables
}
